---
- hosts: cloud
  user: root
  roles:
  - ats-setup
  - ats-demo

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    admin_console_password: '{{hostvars[groups["cloud"][0]].admin_console_password}}'
    post_install: |
      Your ATS cloud is now configured!

      The Web console pasword for admin@{{ account }} user is {{ admin_console_password }}
  roles:
  - ats-finish