---
- name: discover policies
  command: "{{ aws_iam }} list-policies"
  register: list_policies
  changed_when: false

- name: parse policies
  set_fact:
    current_policies: "{{ list_policies.stdout | from_json | json_query('Policies') }}"

- name: discover groups
  command: "{{ aws_iam }} list-groups"
  register: list_groups
  changed_when: false

- name: parse groups
  set_fact:
    current_groups: "{{ list_groups.stdout | from_json | json_query('Groups') }}"

- name: discover users
  command: "{{ aws_iam }} list-users"
  register: list_users
  changed_when: false

- name: parse users
  set_fact:
    current_users: "{{ list_users.stdout | from_json | json_query('Users') }}"

- name: work on groups and policies
  include_tasks: iam-groups.yml
  loop: "{{ demo_groups }}"
  when: ats_demo_state == "present" # create policies and groups before creating users

- name: work on users
  include_tasks: iam-users.yml
  loop: "{{ demo_users }}"

- name: work on groups and policies
  include_tasks: iam-groups.yml
  loop: "{{ demo_groups }}"
  when: ats_demo_state == "absent" # delete policies and groups after deleting users

